### ISSUE TITLE
Fails Under Python 3.7 -- No Error Messages

### ISSUE THREAD

**Issue by jlpoolen** [mberest/onvif-client#1]
I clone the project.  Nothing happens using Python 3.7.  I let it "process" for a minute or more and then finally hit Control-C:

     jlpoole@taurus /usr/local/src/onvif-client $ python3.7 onvifclient.py 
     ^CTraceback (most recent call last):
       File "onvifclient.py", line 104, in <module>
         run()
       File "onvifclient.py", line 41, in run
         data, addr = sock.recvfrom(65536) 
     KeyboardInterrupt
     jlpoole@taurus /usr/local/src/onvif-client $ eix -I zeep
     [I] dev-python/zeep
          Available versions:  3.4.0 {async -tornado PYTHON_TARGETS="python3_6 python3_7"}
          Installed versions:  3.4.0(07:38:36 PM 07/12/2020)(-async -tornado PYTHON_TARGETS="python3_7 -python3_6")
          Homepage:            http://docs.python-zeep.org/
         Description:         A modern/fast Python SOAP client based on lxml / requests
  
     jlpoole@taurus /usr/local/src/onvif-client $

**Comment by mberest** [comment]
Hi!  Before I do anything, I just want to check - if you look at the file onvifclient.py close to the top you'll see a section that says *Edit these variables* ... Did you edit the values of those variables?

**Comment by jlpoolen** [comment]
No, I did not.  I'll review and update.

**Comment by jlpoolen** [comment]
I edited onvifclient.py changing to:

     ##############################################
     ### Edit these variables #####################
     ##############################################
     destinationIP = '192.168.1.48' # the camera ip
     userName = 'admin' # admin, or user, etc...
     password = '[redacted]' # the password for camera
     ##############################################
     ##############################################
     ##############################################

The password above has been redacted but the script does contain the correct password.

     jlpoole@taurus /usr/local/src/onvif-client $ time python3.7 onvifclient.py 
     ^CTraceback (most recent call last):
       File "onvifclient.py", line 104, in <module>
         run()
       File "onvifclient.py", line 41, in run
         data, addr = sock.recvfrom(65536) 
     KeyboardInterrupt
     
     real	2m9.891s
     user	0m0.205s
     sys	0m0.010s
     jlpoole@taurus /usr/local/src/onvif-client $
